### PR TITLE
ADD: `akar-icons-web-components` to README

### PR DESCRIPTION
**Pull request by John-Theo**
Hi, me and my friend @awmleer are huge fans of AkarIcons! We wrote a web components wrapper for AkarIcons, to extend customization capability of AkarIcons and also make AkarIcons be able to used in any framework or vanilla js projects.

If you want to know more about this project, you can take a look at:

- the online [CodePen](https://codepen.io/john-theo/full/LYLddpd)
- our [repo](https://github.com/John-Theo/akar-icons-web-components)
- the [article](https://dev.to/johntheo/lazy-loading-svg-icons-using-web-components-3foi) discussed about this project

### CODE REVIEW

**Comment by John-Theo** [comment]
And besides, would you consider host your svg files to a CDN service like unpkg or jsdelivr? We use lazy loading strategy in this project, and icon svgs are fetched from githubusercontent, CDN hosted SVGs will make our users' lives a lot easier.

**Comment by artcoholic** [comment]
Very cool! Thank you, guys! Added.

**Comment by artcoholic** [comment]
> And besides, would you consider host your svg files to a CDN service like unpkg or jsdelivr? We use lazy loading strategy in this project, and icon svgs are fetched from githubusercontent, CDN hosted SVGs will make our users' lives a lot easier.

I'll look into this.

**Comment by awmleer** [comment]
> I'll look into this.

Actually it is quite simple. Just put the svg files into the npm package `akar-icons`. And then they'll be automatically hosted via services like unpkg.com and jsdelivr.com.

Hope this can help you~

**Comment by artcoholic** [comment]
> > I'll look into this.
> 
> Actually it is quite simple. Just put the svg files into the npm package `akar-icons`. And then they'll be automatically hosted via services like unpkg.com and jsdelivr.com.
> 
> Hope this can help you~

Wouldn't this bloat the npm package?

**Comment by awmleer** [comment]
It will increase the package size about 260 kB (unpacked). Currently the package size 455 kB. It seems not very scaring.

**Comment by artcoholic** [comment]
@John-Theo @awmleer I've published the SVG files here. Does this work for you guys? https://unpkg.com/akar-icons-app@1.0.6/src/svg/air.svg

**Comment by awmleer** [comment]
@artcoholic Thanks a lot!

**Pull request merged**
